//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwmSuite.Proxy.WebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/AlertService.asmx")]
        public string SwmSuite_Proxy_WebService_AlertService_AlertService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_AlertService_AlertService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/CountryService.asmx")]
        public string SwmSuite_Proxy_WebService_CountryService_CountryService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_CountryService_CountryService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/ZipCodeService.asmx")]
        public string SwmSuite_Proxy_WebService_ZipCodeService_ZipCodeService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_ZipCodeService_ZipCodeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/EmployeeService.asmx")]
        public string SwmSuite_Proxy_WebService_EmployeeService_EmployeeService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_EmployeeService_EmployeeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/AvatarService.asmx")]
        public string SwmSuite_Proxy_WebService_AvatarService_AvatarService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_AvatarService_AvatarService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/UserService.asmx")]
        public string SwmSuite_Proxy_WebService_UserService_UserService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_UserService_UserService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/MessageService.asmx")]
        public string SwmSuite_Proxy_WebService_MessageService_MessageService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_MessageService_MessageService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/AgendaService.asmx")]
        public string SwmSuite_Proxy_WebService_AgendaService_AgendaService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_AgendaService_AgendaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/TimeTableService.asmx")]
        public string SwmSuite_Proxy_WebService_TimeTableService_TimeTableService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_TimeTableService_TimeTableService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/TaskService.asmx")]
        public string SwmSuite_Proxy_WebService_TaskService_TaskService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_TaskService_TaskService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/LoggingService.asmx")]
        public string SwmSuite_Proxy_WebService_LoggingService_LoggingService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_LoggingService_LoggingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/ConnectionTestService.asmx")]
        public string SwmSuite_Proxy_WebService_ConnectionTestService_ConnectionTestService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_ConnectionTestService_ConnectionTestService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SWMSuite.Facade.WebService/HolidayService.asmx")]
        public string SwmSuite_Proxy_WebService_HolidayService_HolidayService {
            get {
                return ((string)(this["SwmSuite_Proxy_WebService_HolidayService_HolidayService"]));
            }
        }
    }
}
