//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SwmSuite.Proxy.WebService.TimeTableService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TimeTableServiceSoap", Namespace="SimpleWorkfloorManagementSuiteNameSpace")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessObjectBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeTableTemplateEntry[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeTablePurpose[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeTableEntry[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeTableTemplate[]))]
    public partial class TimeTableService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SwmSuiteSoapHeader swmSuiteSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetTimeTablePurposesForEmployeeGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTimeTablePurposeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTimeTablePurposeOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveTimeTablePurposesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTimeTableEntriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTimeTableEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTimeTableEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveTimeTableEntriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTimeTableTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTimeTableTemplatesForEmployeeGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTimeTableTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTimeTableTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveTimeTableTemplatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTimeTableTemplateEntriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTimeTableTemplateEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTimeTableTemplateEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveTimeTableTemplateEntriesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TimeTableService() {
            this.Url = global::SwmSuite.Proxy.WebService.Properties.Settings.Default.SwmSuite_Proxy_WebService_TimeTableService_TimeTableService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SwmSuiteSoapHeader SwmSuiteSoapHeaderValue {
            get {
                return this.swmSuiteSoapHeaderValueField;
            }
            set {
                this.swmSuiteSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTimeTablePurposesForEmployeeGroupCompletedEventHandler GetTimeTablePurposesForEmployeeGroupCompleted;
        
        /// <remarks/>
        public event CreateTimeTablePurposeCompletedEventHandler CreateTimeTablePurposeCompleted;
        
        /// <remarks/>
        public event UpdateTimeTablePurposeCompletedEventHandler UpdateTimeTablePurposeCompleted;
        
        /// <remarks/>
        public event RemoveTimeTablePurposesCompletedEventHandler RemoveTimeTablePurposesCompleted;
        
        /// <remarks/>
        public event GetTimeTableEntriesCompletedEventHandler GetTimeTableEntriesCompleted;
        
        /// <remarks/>
        public event CreateTimeTableEntryCompletedEventHandler CreateTimeTableEntryCompleted;
        
        /// <remarks/>
        public event UpdateTimeTableEntryCompletedEventHandler UpdateTimeTableEntryCompleted;
        
        /// <remarks/>
        public event RemoveTimeTableEntriesCompletedEventHandler RemoveTimeTableEntriesCompleted;
        
        /// <remarks/>
        public event GetTimeTableTemplateCompletedEventHandler GetTimeTableTemplateCompleted;
        
        /// <remarks/>
        public event GetTimeTableTemplatesForEmployeeGroupCompletedEventHandler GetTimeTableTemplatesForEmployeeGroupCompleted;
        
        /// <remarks/>
        public event CreateTimeTableTemplateCompletedEventHandler CreateTimeTableTemplateCompleted;
        
        /// <remarks/>
        public event UpdateTimeTableTemplateCompletedEventHandler UpdateTimeTableTemplateCompleted;
        
        /// <remarks/>
        public event RemoveTimeTableTemplatesCompletedEventHandler RemoveTimeTableTemplatesCompleted;
        
        /// <remarks/>
        public event GetTimeTableTemplateEntriesCompletedEventHandler GetTimeTableTemplateEntriesCompleted;
        
        /// <remarks/>
        public event CreateTimeTableTemplateEntryCompletedEventHandler CreateTimeTableTemplateEntryCompleted;
        
        /// <remarks/>
        public event UpdateTimeTableTemplateEntryCompletedEventHandler UpdateTimeTableTemplateEntryCompleted;
        
        /// <remarks/>
        public event RemoveTimeTableTemplateEntriesCompletedEventHandler RemoveTimeTableTemplateEntriesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetTimeTablePurposesForEmployeeGroup", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTablePurpose[] GetTimeTablePurposesForEmployeeGroup(EmployeeGroup employeeGroup) {
            object[] results = this.Invoke("GetTimeTablePurposesForEmployeeGroup", new object[] {
                        employeeGroup});
            return ((TimeTablePurpose[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTimeTablePurposesForEmployeeGroupAsync(EmployeeGroup employeeGroup) {
            this.GetTimeTablePurposesForEmployeeGroupAsync(employeeGroup, null);
        }
        
        /// <remarks/>
        public void GetTimeTablePurposesForEmployeeGroupAsync(EmployeeGroup employeeGroup, object userState) {
            if ((this.GetTimeTablePurposesForEmployeeGroupOperationCompleted == null)) {
                this.GetTimeTablePurposesForEmployeeGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimeTablePurposesForEmployeeGroupOperationCompleted);
            }
            this.InvokeAsync("GetTimeTablePurposesForEmployeeGroup", new object[] {
                        employeeGroup}, this.GetTimeTablePurposesForEmployeeGroupOperationCompleted, userState);
        }
        
        private void OnGetTimeTablePurposesForEmployeeGroupOperationCompleted(object arg) {
            if ((this.GetTimeTablePurposesForEmployeeGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimeTablePurposesForEmployeeGroupCompleted(this, new GetTimeTablePurposesForEmployeeGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/CreateTimeTablePurpose", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTablePurpose CreateTimeTablePurpose(TimeTablePurpose timeTablePurpose, EmployeeGroup employeeGroup) {
            object[] results = this.Invoke("CreateTimeTablePurpose", new object[] {
                        timeTablePurpose,
                        employeeGroup});
            return ((TimeTablePurpose)(results[0]));
        }
        
        /// <remarks/>
        public void CreateTimeTablePurposeAsync(TimeTablePurpose timeTablePurpose, EmployeeGroup employeeGroup) {
            this.CreateTimeTablePurposeAsync(timeTablePurpose, employeeGroup, null);
        }
        
        /// <remarks/>
        public void CreateTimeTablePurposeAsync(TimeTablePurpose timeTablePurpose, EmployeeGroup employeeGroup, object userState) {
            if ((this.CreateTimeTablePurposeOperationCompleted == null)) {
                this.CreateTimeTablePurposeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTimeTablePurposeOperationCompleted);
            }
            this.InvokeAsync("CreateTimeTablePurpose", new object[] {
                        timeTablePurpose,
                        employeeGroup}, this.CreateTimeTablePurposeOperationCompleted, userState);
        }
        
        private void OnCreateTimeTablePurposeOperationCompleted(object arg) {
            if ((this.CreateTimeTablePurposeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTimeTablePurposeCompleted(this, new CreateTimeTablePurposeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/UpdateTimeTablePurpose", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTablePurpose UpdateTimeTablePurpose(TimeTablePurpose timeTablePurpose, EmployeeGroup employeeGroup) {
            object[] results = this.Invoke("UpdateTimeTablePurpose", new object[] {
                        timeTablePurpose,
                        employeeGroup});
            return ((TimeTablePurpose)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTimeTablePurposeAsync(TimeTablePurpose timeTablePurpose, EmployeeGroup employeeGroup) {
            this.UpdateTimeTablePurposeAsync(timeTablePurpose, employeeGroup, null);
        }
        
        /// <remarks/>
        public void UpdateTimeTablePurposeAsync(TimeTablePurpose timeTablePurpose, EmployeeGroup employeeGroup, object userState) {
            if ((this.UpdateTimeTablePurposeOperationCompleted == null)) {
                this.UpdateTimeTablePurposeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTimeTablePurposeOperationCompleted);
            }
            this.InvokeAsync("UpdateTimeTablePurpose", new object[] {
                        timeTablePurpose,
                        employeeGroup}, this.UpdateTimeTablePurposeOperationCompleted, userState);
        }
        
        private void OnUpdateTimeTablePurposeOperationCompleted(object arg) {
            if ((this.UpdateTimeTablePurposeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTimeTablePurposeCompleted(this, new UpdateTimeTablePurposeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/RemoveTimeTablePurposes", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveTimeTablePurposes(TimeTablePurpose[] timeTablePurposes) {
            this.Invoke("RemoveTimeTablePurposes", new object[] {
                        timeTablePurposes});
        }
        
        /// <remarks/>
        public void RemoveTimeTablePurposesAsync(TimeTablePurpose[] timeTablePurposes) {
            this.RemoveTimeTablePurposesAsync(timeTablePurposes, null);
        }
        
        /// <remarks/>
        public void RemoveTimeTablePurposesAsync(TimeTablePurpose[] timeTablePurposes, object userState) {
            if ((this.RemoveTimeTablePurposesOperationCompleted == null)) {
                this.RemoveTimeTablePurposesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveTimeTablePurposesOperationCompleted);
            }
            this.InvokeAsync("RemoveTimeTablePurposes", new object[] {
                        timeTablePurposes}, this.RemoveTimeTablePurposesOperationCompleted, userState);
        }
        
        private void OnRemoveTimeTablePurposesOperationCompleted(object arg) {
            if ((this.RemoveTimeTablePurposesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveTimeTablePurposesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetTimeTableEntries", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTableEntry[] GetTimeTableEntries(Employee employee, System.DateTime begin, System.DateTime end) {
            object[] results = this.Invoke("GetTimeTableEntries", new object[] {
                        employee,
                        begin,
                        end});
            return ((TimeTableEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTimeTableEntriesAsync(Employee employee, System.DateTime begin, System.DateTime end) {
            this.GetTimeTableEntriesAsync(employee, begin, end, null);
        }
        
        /// <remarks/>
        public void GetTimeTableEntriesAsync(Employee employee, System.DateTime begin, System.DateTime end, object userState) {
            if ((this.GetTimeTableEntriesOperationCompleted == null)) {
                this.GetTimeTableEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimeTableEntriesOperationCompleted);
            }
            this.InvokeAsync("GetTimeTableEntries", new object[] {
                        employee,
                        begin,
                        end}, this.GetTimeTableEntriesOperationCompleted, userState);
        }
        
        private void OnGetTimeTableEntriesOperationCompleted(object arg) {
            if ((this.GetTimeTableEntriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimeTableEntriesCompleted(this, new GetTimeTableEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/CreateTimeTableEntry", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTableEntry CreateTimeTableEntry(TimeTableEntry timeTableEntry) {
            object[] results = this.Invoke("CreateTimeTableEntry", new object[] {
                        timeTableEntry});
            return ((TimeTableEntry)(results[0]));
        }
        
        /// <remarks/>
        public void CreateTimeTableEntryAsync(TimeTableEntry timeTableEntry) {
            this.CreateTimeTableEntryAsync(timeTableEntry, null);
        }
        
        /// <remarks/>
        public void CreateTimeTableEntryAsync(TimeTableEntry timeTableEntry, object userState) {
            if ((this.CreateTimeTableEntryOperationCompleted == null)) {
                this.CreateTimeTableEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTimeTableEntryOperationCompleted);
            }
            this.InvokeAsync("CreateTimeTableEntry", new object[] {
                        timeTableEntry}, this.CreateTimeTableEntryOperationCompleted, userState);
        }
        
        private void OnCreateTimeTableEntryOperationCompleted(object arg) {
            if ((this.CreateTimeTableEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTimeTableEntryCompleted(this, new CreateTimeTableEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/UpdateTimeTableEntry", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTableEntry UpdateTimeTableEntry(TimeTableEntry timeTableEntry) {
            object[] results = this.Invoke("UpdateTimeTableEntry", new object[] {
                        timeTableEntry});
            return ((TimeTableEntry)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTimeTableEntryAsync(TimeTableEntry timeTableEntry) {
            this.UpdateTimeTableEntryAsync(timeTableEntry, null);
        }
        
        /// <remarks/>
        public void UpdateTimeTableEntryAsync(TimeTableEntry timeTableEntry, object userState) {
            if ((this.UpdateTimeTableEntryOperationCompleted == null)) {
                this.UpdateTimeTableEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTimeTableEntryOperationCompleted);
            }
            this.InvokeAsync("UpdateTimeTableEntry", new object[] {
                        timeTableEntry}, this.UpdateTimeTableEntryOperationCompleted, userState);
        }
        
        private void OnUpdateTimeTableEntryOperationCompleted(object arg) {
            if ((this.UpdateTimeTableEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTimeTableEntryCompleted(this, new UpdateTimeTableEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/RemoveTimeTableEntries", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveTimeTableEntries(TimeTableEntry[] timeTableEntries) {
            this.Invoke("RemoveTimeTableEntries", new object[] {
                        timeTableEntries});
        }
        
        /// <remarks/>
        public void RemoveTimeTableEntriesAsync(TimeTableEntry[] timeTableEntries) {
            this.RemoveTimeTableEntriesAsync(timeTableEntries, null);
        }
        
        /// <remarks/>
        public void RemoveTimeTableEntriesAsync(TimeTableEntry[] timeTableEntries, object userState) {
            if ((this.RemoveTimeTableEntriesOperationCompleted == null)) {
                this.RemoveTimeTableEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveTimeTableEntriesOperationCompleted);
            }
            this.InvokeAsync("RemoveTimeTableEntries", new object[] {
                        timeTableEntries}, this.RemoveTimeTableEntriesOperationCompleted, userState);
        }
        
        private void OnRemoveTimeTableEntriesOperationCompleted(object arg) {
            if ((this.RemoveTimeTableEntriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveTimeTableEntriesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetTimeTableTemplate", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTableTemplate GetTimeTableTemplate(int timeTableTemplateSysId) {
            object[] results = this.Invoke("GetTimeTableTemplate", new object[] {
                        timeTableTemplateSysId});
            return ((TimeTableTemplate)(results[0]));
        }
        
        /// <remarks/>
        public void GetTimeTableTemplateAsync(int timeTableTemplateSysId) {
            this.GetTimeTableTemplateAsync(timeTableTemplateSysId, null);
        }
        
        /// <remarks/>
        public void GetTimeTableTemplateAsync(int timeTableTemplateSysId, object userState) {
            if ((this.GetTimeTableTemplateOperationCompleted == null)) {
                this.GetTimeTableTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimeTableTemplateOperationCompleted);
            }
            this.InvokeAsync("GetTimeTableTemplate", new object[] {
                        timeTableTemplateSysId}, this.GetTimeTableTemplateOperationCompleted, userState);
        }
        
        private void OnGetTimeTableTemplateOperationCompleted(object arg) {
            if ((this.GetTimeTableTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimeTableTemplateCompleted(this, new GetTimeTableTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetTimeTableTemplatesForEmployeeGroup", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTableTemplate[] GetTimeTableTemplatesForEmployeeGroup(EmployeeGroup employeeGroup) {
            object[] results = this.Invoke("GetTimeTableTemplatesForEmployeeGroup", new object[] {
                        employeeGroup});
            return ((TimeTableTemplate[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTimeTableTemplatesForEmployeeGroupAsync(EmployeeGroup employeeGroup) {
            this.GetTimeTableTemplatesForEmployeeGroupAsync(employeeGroup, null);
        }
        
        /// <remarks/>
        public void GetTimeTableTemplatesForEmployeeGroupAsync(EmployeeGroup employeeGroup, object userState) {
            if ((this.GetTimeTableTemplatesForEmployeeGroupOperationCompleted == null)) {
                this.GetTimeTableTemplatesForEmployeeGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimeTableTemplatesForEmployeeGroupOperationCompleted);
            }
            this.InvokeAsync("GetTimeTableTemplatesForEmployeeGroup", new object[] {
                        employeeGroup}, this.GetTimeTableTemplatesForEmployeeGroupOperationCompleted, userState);
        }
        
        private void OnGetTimeTableTemplatesForEmployeeGroupOperationCompleted(object arg) {
            if ((this.GetTimeTableTemplatesForEmployeeGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimeTableTemplatesForEmployeeGroupCompleted(this, new GetTimeTableTemplatesForEmployeeGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/CreateTimeTableTemplate", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTableTemplate CreateTimeTableTemplate(TimeTableTemplate timeTableTemplate, EmployeeGroup employeeGroup) {
            object[] results = this.Invoke("CreateTimeTableTemplate", new object[] {
                        timeTableTemplate,
                        employeeGroup});
            return ((TimeTableTemplate)(results[0]));
        }
        
        /// <remarks/>
        public void CreateTimeTableTemplateAsync(TimeTableTemplate timeTableTemplate, EmployeeGroup employeeGroup) {
            this.CreateTimeTableTemplateAsync(timeTableTemplate, employeeGroup, null);
        }
        
        /// <remarks/>
        public void CreateTimeTableTemplateAsync(TimeTableTemplate timeTableTemplate, EmployeeGroup employeeGroup, object userState) {
            if ((this.CreateTimeTableTemplateOperationCompleted == null)) {
                this.CreateTimeTableTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTimeTableTemplateOperationCompleted);
            }
            this.InvokeAsync("CreateTimeTableTemplate", new object[] {
                        timeTableTemplate,
                        employeeGroup}, this.CreateTimeTableTemplateOperationCompleted, userState);
        }
        
        private void OnCreateTimeTableTemplateOperationCompleted(object arg) {
            if ((this.CreateTimeTableTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTimeTableTemplateCompleted(this, new CreateTimeTableTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/UpdateTimeTableTemplate", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTableTemplate UpdateTimeTableTemplate(TimeTableTemplate timeTableTemplate, EmployeeGroup employeeGroup) {
            object[] results = this.Invoke("UpdateTimeTableTemplate", new object[] {
                        timeTableTemplate,
                        employeeGroup});
            return ((TimeTableTemplate)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTimeTableTemplateAsync(TimeTableTemplate timeTableTemplate, EmployeeGroup employeeGroup) {
            this.UpdateTimeTableTemplateAsync(timeTableTemplate, employeeGroup, null);
        }
        
        /// <remarks/>
        public void UpdateTimeTableTemplateAsync(TimeTableTemplate timeTableTemplate, EmployeeGroup employeeGroup, object userState) {
            if ((this.UpdateTimeTableTemplateOperationCompleted == null)) {
                this.UpdateTimeTableTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTimeTableTemplateOperationCompleted);
            }
            this.InvokeAsync("UpdateTimeTableTemplate", new object[] {
                        timeTableTemplate,
                        employeeGroup}, this.UpdateTimeTableTemplateOperationCompleted, userState);
        }
        
        private void OnUpdateTimeTableTemplateOperationCompleted(object arg) {
            if ((this.UpdateTimeTableTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTimeTableTemplateCompleted(this, new UpdateTimeTableTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/RemoveTimeTableTemplates", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveTimeTableTemplates(TimeTableTemplate[] timeTableTemplates) {
            this.Invoke("RemoveTimeTableTemplates", new object[] {
                        timeTableTemplates});
        }
        
        /// <remarks/>
        public void RemoveTimeTableTemplatesAsync(TimeTableTemplate[] timeTableTemplates) {
            this.RemoveTimeTableTemplatesAsync(timeTableTemplates, null);
        }
        
        /// <remarks/>
        public void RemoveTimeTableTemplatesAsync(TimeTableTemplate[] timeTableTemplates, object userState) {
            if ((this.RemoveTimeTableTemplatesOperationCompleted == null)) {
                this.RemoveTimeTableTemplatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveTimeTableTemplatesOperationCompleted);
            }
            this.InvokeAsync("RemoveTimeTableTemplates", new object[] {
                        timeTableTemplates}, this.RemoveTimeTableTemplatesOperationCompleted, userState);
        }
        
        private void OnRemoveTimeTableTemplatesOperationCompleted(object arg) {
            if ((this.RemoveTimeTableTemplatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveTimeTableTemplatesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetTimeTableTemplateEntries", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTableTemplateEntry[] GetTimeTableTemplateEntries(TimeTableTemplate timeTableTemplate) {
            object[] results = this.Invoke("GetTimeTableTemplateEntries", new object[] {
                        timeTableTemplate});
            return ((TimeTableTemplateEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTimeTableTemplateEntriesAsync(TimeTableTemplate timeTableTemplate) {
            this.GetTimeTableTemplateEntriesAsync(timeTableTemplate, null);
        }
        
        /// <remarks/>
        public void GetTimeTableTemplateEntriesAsync(TimeTableTemplate timeTableTemplate, object userState) {
            if ((this.GetTimeTableTemplateEntriesOperationCompleted == null)) {
                this.GetTimeTableTemplateEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimeTableTemplateEntriesOperationCompleted);
            }
            this.InvokeAsync("GetTimeTableTemplateEntries", new object[] {
                        timeTableTemplate}, this.GetTimeTableTemplateEntriesOperationCompleted, userState);
        }
        
        private void OnGetTimeTableTemplateEntriesOperationCompleted(object arg) {
            if ((this.GetTimeTableTemplateEntriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimeTableTemplateEntriesCompleted(this, new GetTimeTableTemplateEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/CreateTimeTableTemplateEntry", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTableTemplateEntry CreateTimeTableTemplateEntry(TimeTableTemplateEntry timeTableTemplateEntry, TimeTableTemplate timeTableTemplate) {
            object[] results = this.Invoke("CreateTimeTableTemplateEntry", new object[] {
                        timeTableTemplateEntry,
                        timeTableTemplate});
            return ((TimeTableTemplateEntry)(results[0]));
        }
        
        /// <remarks/>
        public void CreateTimeTableTemplateEntryAsync(TimeTableTemplateEntry timeTableTemplateEntry, TimeTableTemplate timeTableTemplate) {
            this.CreateTimeTableTemplateEntryAsync(timeTableTemplateEntry, timeTableTemplate, null);
        }
        
        /// <remarks/>
        public void CreateTimeTableTemplateEntryAsync(TimeTableTemplateEntry timeTableTemplateEntry, TimeTableTemplate timeTableTemplate, object userState) {
            if ((this.CreateTimeTableTemplateEntryOperationCompleted == null)) {
                this.CreateTimeTableTemplateEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTimeTableTemplateEntryOperationCompleted);
            }
            this.InvokeAsync("CreateTimeTableTemplateEntry", new object[] {
                        timeTableTemplateEntry,
                        timeTableTemplate}, this.CreateTimeTableTemplateEntryOperationCompleted, userState);
        }
        
        private void OnCreateTimeTableTemplateEntryOperationCompleted(object arg) {
            if ((this.CreateTimeTableTemplateEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTimeTableTemplateEntryCompleted(this, new CreateTimeTableTemplateEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/UpdateTimeTableTemplateEntry", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeTableTemplateEntry UpdateTimeTableTemplateEntry(TimeTableTemplateEntry timeTableTemplateEntry) {
            object[] results = this.Invoke("UpdateTimeTableTemplateEntry", new object[] {
                        timeTableTemplateEntry});
            return ((TimeTableTemplateEntry)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTimeTableTemplateEntryAsync(TimeTableTemplateEntry timeTableTemplateEntry) {
            this.UpdateTimeTableTemplateEntryAsync(timeTableTemplateEntry, null);
        }
        
        /// <remarks/>
        public void UpdateTimeTableTemplateEntryAsync(TimeTableTemplateEntry timeTableTemplateEntry, object userState) {
            if ((this.UpdateTimeTableTemplateEntryOperationCompleted == null)) {
                this.UpdateTimeTableTemplateEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTimeTableTemplateEntryOperationCompleted);
            }
            this.InvokeAsync("UpdateTimeTableTemplateEntry", new object[] {
                        timeTableTemplateEntry}, this.UpdateTimeTableTemplateEntryOperationCompleted, userState);
        }
        
        private void OnUpdateTimeTableTemplateEntryOperationCompleted(object arg) {
            if ((this.UpdateTimeTableTemplateEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTimeTableTemplateEntryCompleted(this, new UpdateTimeTableTemplateEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/RemoveTimeTableTemplateEntries", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveTimeTableTemplateEntries(TimeTableTemplateEntry[] timeTableTemplateEntries) {
            this.Invoke("RemoveTimeTableTemplateEntries", new object[] {
                        timeTableTemplateEntries});
        }
        
        /// <remarks/>
        public void RemoveTimeTableTemplateEntriesAsync(TimeTableTemplateEntry[] timeTableTemplateEntries) {
            this.RemoveTimeTableTemplateEntriesAsync(timeTableTemplateEntries, null);
        }
        
        /// <remarks/>
        public void RemoveTimeTableTemplateEntriesAsync(TimeTableTemplateEntry[] timeTableTemplateEntries, object userState) {
            if ((this.RemoveTimeTableTemplateEntriesOperationCompleted == null)) {
                this.RemoveTimeTableTemplateEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveTimeTableTemplateEntriesOperationCompleted);
            }
            this.InvokeAsync("RemoveTimeTableTemplateEntries", new object[] {
                        timeTableTemplateEntries}, this.RemoveTimeTableTemplateEntriesOperationCompleted, userState);
        }
        
        private void OnRemoveTimeTableTemplateEntriesOperationCompleted(object arg) {
            if ((this.RemoveTimeTableTemplateEntriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveTimeTableTemplateEntriesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SimpleWorkfloorManagementSuiteNameSpace")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="SimpleWorkfloorManagementSuiteNameSpace", IsNullable=false)]
    public partial class SwmSuiteSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private int employeeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeTableTemplateEntry))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeTableTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeTableEntry))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeTablePurpose))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmployeeSettings))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Avatar))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZipCode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmployeeGroup))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class BusinessObjectBase {
        
        private int sysIdField;
        
        private int rowVersionField;
        
        private string[] validationErrorsField;
        
        /// <remarks/>
        public int SysId {
            get {
                return this.sysIdField;
            }
            set {
                this.sysIdField = value;
            }
        }
        
        /// <remarks/>
        public int RowVersion {
            get {
                return this.rowVersionField;
            }
            set {
                this.rowVersionField = value;
            }
        }
        
        /// <remarks/>
        public string[] ValidationErrors {
            get {
                return this.validationErrorsField;
            }
            set {
                this.validationErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class TimeTableTemplateEntry : BusinessObjectBase {
        
        private System.DateTime dateField;
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private TimeTablePurpose timeTablePurposeField;
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public TimeTablePurpose TimeTablePurpose {
            get {
                return this.timeTablePurposeField;
            }
            set {
                this.timeTablePurposeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class TimeTablePurpose : BusinessObjectBase {
        
        private string descriptionField;
        
        private int legendaColor1Field;
        
        private int legendaColor2Field;
        
        private int legendaColor3Field;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int LegendaColor1 {
            get {
                return this.legendaColor1Field;
            }
            set {
                this.legendaColor1Field = value;
            }
        }
        
        /// <remarks/>
        public int LegendaColor2 {
            get {
                return this.legendaColor2Field;
            }
            set {
                this.legendaColor2Field = value;
            }
        }
        
        /// <remarks/>
        public int LegendaColor3 {
            get {
                return this.legendaColor3Field;
            }
            set {
                this.legendaColor3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class TimeTableTemplate : BusinessObjectBase {
        
        private string nameField;
        
        private string descriptionField;
        
        private EmployeeGroup employeeGroupField;
        
        private TimeTableTemplateEntry[] timeTableTemplateEntriesField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public EmployeeGroup EmployeeGroup {
            get {
                return this.employeeGroupField;
            }
            set {
                this.employeeGroupField = value;
            }
        }
        
        /// <remarks/>
        public TimeTableTemplateEntry[] TimeTableTemplateEntries {
            get {
                return this.timeTableTemplateEntriesField;
            }
            set {
                this.timeTableTemplateEntriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class EmployeeGroup : BusinessObjectBase {
        
        private string nameField;
        
        private string descriptionField;
        
        private Employee[] employeesField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Employee[] Employees {
            get {
                return this.employeesField;
            }
            set {
                this.employeesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class Employee : BusinessObjectBase {
        
        private System.Guid userSysIdField;
        
        private string nameField;
        
        private string firstNameField;
        
        private string addressField;
        
        private ZipCode zipCodeField;
        
        private string privatePhoneNumberField;
        
        private string workPhoneNumberField;
        
        private string cellPhoneNumberField;
        
        private string emailAddress1Field;
        
        private string emailAddress2Field;
        
        private string emailAddress3Field;
        
        private string emailAddress4Field;
        
        private string emailAddress5Field;
        
        private Avatar avatarField;
        
        private EmployeeSettings settingsField;
        
        private string userNameField;
        
        private string passwordField;
        
        private bool administratorField;
        
        /// <remarks/>
        public System.Guid UserSysId {
            get {
                return this.userSysIdField;
            }
            set {
                this.userSysIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public ZipCode ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PrivatePhoneNumber {
            get {
                return this.privatePhoneNumberField;
            }
            set {
                this.privatePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPhoneNumber {
            get {
                return this.workPhoneNumberField;
            }
            set {
                this.workPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CellPhoneNumber {
            get {
                return this.cellPhoneNumberField;
            }
            set {
                this.cellPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress1 {
            get {
                return this.emailAddress1Field;
            }
            set {
                this.emailAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress2 {
            get {
                return this.emailAddress2Field;
            }
            set {
                this.emailAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress3 {
            get {
                return this.emailAddress3Field;
            }
            set {
                this.emailAddress3Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress4 {
            get {
                return this.emailAddress4Field;
            }
            set {
                this.emailAddress4Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress5 {
            get {
                return this.emailAddress5Field;
            }
            set {
                this.emailAddress5Field = value;
            }
        }
        
        /// <remarks/>
        public Avatar Avatar {
            get {
                return this.avatarField;
            }
            set {
                this.avatarField = value;
            }
        }
        
        /// <remarks/>
        public EmployeeSettings Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool Administrator {
            get {
                return this.administratorField;
            }
            set {
                this.administratorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class ZipCode : BusinessObjectBase {
        
        private string codeField;
        
        private string cityField;
        
        private string countryField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class Avatar : BusinessObjectBase {
        
        private byte[] pictureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class EmployeeSettings : BusinessObjectBase {
        
        private bool autoLogonField;
        
        private string autoLogonHostField;
        
        private int logoutTimeoutField;
        
        private bool emailNotificationField;
        
        private string emailAddressField;
        
        private string smtpServerField;
        
        private System.Nullable<int> smtpPortField;
        
        private bool secureConnectionField;
        
        private bool authenticationField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public bool AutoLogon {
            get {
                return this.autoLogonField;
            }
            set {
                this.autoLogonField = value;
            }
        }
        
        /// <remarks/>
        public string AutoLogonHost {
            get {
                return this.autoLogonHostField;
            }
            set {
                this.autoLogonHostField = value;
            }
        }
        
        /// <remarks/>
        public int LogoutTimeout {
            get {
                return this.logoutTimeoutField;
            }
            set {
                this.logoutTimeoutField = value;
            }
        }
        
        /// <remarks/>
        public bool EmailNotification {
            get {
                return this.emailNotificationField;
            }
            set {
                this.emailNotificationField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string SmtpServer {
            get {
                return this.smtpServerField;
            }
            set {
                this.smtpServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SmtpPort {
            get {
                return this.smtpPortField;
            }
            set {
                this.smtpPortField = value;
            }
        }
        
        /// <remarks/>
        public bool SecureConnection {
            get {
                return this.secureConnectionField;
            }
            set {
                this.secureConnectionField = value;
            }
        }
        
        /// <remarks/>
        public bool Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class TimeTableEntry : BusinessObjectBase {
        
        private System.DateTime dateField;
        
        private Employee employeeField;
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private TimeTablePurpose timeTablePurposeField;
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public Employee Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public TimeTablePurpose TimeTablePurpose {
            get {
                return this.timeTablePurposeField;
            }
            set {
                this.timeTablePurposeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetTimeTablePurposesForEmployeeGroupCompletedEventHandler(object sender, GetTimeTablePurposesForEmployeeGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimeTablePurposesForEmployeeGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimeTablePurposesForEmployeeGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTablePurpose[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTablePurpose[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateTimeTablePurposeCompletedEventHandler(object sender, CreateTimeTablePurposeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTimeTablePurposeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTimeTablePurposeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTablePurpose Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTablePurpose)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateTimeTablePurposeCompletedEventHandler(object sender, UpdateTimeTablePurposeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTimeTablePurposeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTimeTablePurposeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTablePurpose Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTablePurpose)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RemoveTimeTablePurposesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetTimeTableEntriesCompletedEventHandler(object sender, GetTimeTableEntriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimeTableEntriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimeTableEntriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTableEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTableEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateTimeTableEntryCompletedEventHandler(object sender, CreateTimeTableEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTimeTableEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTimeTableEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTableEntry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTableEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateTimeTableEntryCompletedEventHandler(object sender, UpdateTimeTableEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTimeTableEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTimeTableEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTableEntry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTableEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RemoveTimeTableEntriesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetTimeTableTemplateCompletedEventHandler(object sender, GetTimeTableTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimeTableTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimeTableTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTableTemplate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTableTemplate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetTimeTableTemplatesForEmployeeGroupCompletedEventHandler(object sender, GetTimeTableTemplatesForEmployeeGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimeTableTemplatesForEmployeeGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimeTableTemplatesForEmployeeGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTableTemplate[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTableTemplate[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateTimeTableTemplateCompletedEventHandler(object sender, CreateTimeTableTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTimeTableTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTimeTableTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTableTemplate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTableTemplate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateTimeTableTemplateCompletedEventHandler(object sender, UpdateTimeTableTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTimeTableTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTimeTableTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTableTemplate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTableTemplate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RemoveTimeTableTemplatesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetTimeTableTemplateEntriesCompletedEventHandler(object sender, GetTimeTableTemplateEntriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimeTableTemplateEntriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimeTableTemplateEntriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTableTemplateEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTableTemplateEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateTimeTableTemplateEntryCompletedEventHandler(object sender, CreateTimeTableTemplateEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTimeTableTemplateEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTimeTableTemplateEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTableTemplateEntry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTableTemplateEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateTimeTableTemplateEntryCompletedEventHandler(object sender, UpdateTimeTableTemplateEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTimeTableTemplateEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTimeTableTemplateEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeTableTemplateEntry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeTableTemplateEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RemoveTimeTableTemplateEntriesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591