//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SwmSuite.Proxy.WebService.AlertService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AlertServiceSoap", Namespace="SimpleWorkfloorManagementSuiteNameSpace")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessObjectBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmployeeGroup[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Alert[]))]
    public partial class AlertService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SwmSuiteSoapHeader swmSuiteSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetAlertsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGlobalAlertsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAlertsForEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAlertsForEmployeeGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveAlertsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AlertService() {
            this.Url = global::SwmSuite.Proxy.WebService.Properties.Settings.Default.SwmSuite_Proxy_WebService_AlertService_AlertService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SwmSuiteSoapHeader SwmSuiteSoapHeaderValue {
            get {
                return this.swmSuiteSoapHeaderValueField;
            }
            set {
                this.swmSuiteSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAlertsCompletedEventHandler GetAlertsCompleted;
        
        /// <remarks/>
        public event GetGlobalAlertsCompletedEventHandler GetGlobalAlertsCompleted;
        
        /// <remarks/>
        public event GetAlertsForEmployeeCompletedEventHandler GetAlertsForEmployeeCompleted;
        
        /// <remarks/>
        public event GetAlertsForEmployeeGroupCompletedEventHandler GetAlertsForEmployeeGroupCompleted;
        
        /// <remarks/>
        public event CreateAlertCompletedEventHandler CreateAlertCompleted;
        
        /// <remarks/>
        public event UpdateAlertCompletedEventHandler UpdateAlertCompleted;
        
        /// <remarks/>
        public event RemoveAlertsCompletedEventHandler RemoveAlertsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetAlerts", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Alert[] GetAlerts() {
            object[] results = this.Invoke("GetAlerts", new object[0]);
            return ((Alert[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAlertsAsync() {
            this.GetAlertsAsync(null);
        }
        
        /// <remarks/>
        public void GetAlertsAsync(object userState) {
            if ((this.GetAlertsOperationCompleted == null)) {
                this.GetAlertsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAlertsOperationCompleted);
            }
            this.InvokeAsync("GetAlerts", new object[0], this.GetAlertsOperationCompleted, userState);
        }
        
        private void OnGetAlertsOperationCompleted(object arg) {
            if ((this.GetAlertsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAlertsCompleted(this, new GetAlertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetGlobalAlerts", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Alert[] GetGlobalAlerts() {
            object[] results = this.Invoke("GetGlobalAlerts", new object[0]);
            return ((Alert[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGlobalAlertsAsync() {
            this.GetGlobalAlertsAsync(null);
        }
        
        /// <remarks/>
        public void GetGlobalAlertsAsync(object userState) {
            if ((this.GetGlobalAlertsOperationCompleted == null)) {
                this.GetGlobalAlertsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGlobalAlertsOperationCompleted);
            }
            this.InvokeAsync("GetGlobalAlerts", new object[0], this.GetGlobalAlertsOperationCompleted, userState);
        }
        
        private void OnGetGlobalAlertsOperationCompleted(object arg) {
            if ((this.GetGlobalAlertsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGlobalAlertsCompleted(this, new GetGlobalAlertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetAlertsForEmployee", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Alert[] GetAlertsForEmployee(Employee employee) {
            object[] results = this.Invoke("GetAlertsForEmployee", new object[] {
                        employee});
            return ((Alert[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAlertsForEmployeeAsync(Employee employee) {
            this.GetAlertsForEmployeeAsync(employee, null);
        }
        
        /// <remarks/>
        public void GetAlertsForEmployeeAsync(Employee employee, object userState) {
            if ((this.GetAlertsForEmployeeOperationCompleted == null)) {
                this.GetAlertsForEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAlertsForEmployeeOperationCompleted);
            }
            this.InvokeAsync("GetAlertsForEmployee", new object[] {
                        employee}, this.GetAlertsForEmployeeOperationCompleted, userState);
        }
        
        private void OnGetAlertsForEmployeeOperationCompleted(object arg) {
            if ((this.GetAlertsForEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAlertsForEmployeeCompleted(this, new GetAlertsForEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetAlertsForEmployeeGroup", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Alert[] GetAlertsForEmployeeGroup(EmployeeGroup employeeGroup) {
            object[] results = this.Invoke("GetAlertsForEmployeeGroup", new object[] {
                        employeeGroup});
            return ((Alert[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAlertsForEmployeeGroupAsync(EmployeeGroup employeeGroup) {
            this.GetAlertsForEmployeeGroupAsync(employeeGroup, null);
        }
        
        /// <remarks/>
        public void GetAlertsForEmployeeGroupAsync(EmployeeGroup employeeGroup, object userState) {
            if ((this.GetAlertsForEmployeeGroupOperationCompleted == null)) {
                this.GetAlertsForEmployeeGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAlertsForEmployeeGroupOperationCompleted);
            }
            this.InvokeAsync("GetAlertsForEmployeeGroup", new object[] {
                        employeeGroup}, this.GetAlertsForEmployeeGroupOperationCompleted, userState);
        }
        
        private void OnGetAlertsForEmployeeGroupOperationCompleted(object arg) {
            if ((this.GetAlertsForEmployeeGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAlertsForEmployeeGroupCompleted(this, new GetAlertsForEmployeeGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/CreateAlert", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateAlert(Alert alert) {
            this.Invoke("CreateAlert", new object[] {
                        alert});
        }
        
        /// <remarks/>
        public void CreateAlertAsync(Alert alert) {
            this.CreateAlertAsync(alert, null);
        }
        
        /// <remarks/>
        public void CreateAlertAsync(Alert alert, object userState) {
            if ((this.CreateAlertOperationCompleted == null)) {
                this.CreateAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAlertOperationCompleted);
            }
            this.InvokeAsync("CreateAlert", new object[] {
                        alert}, this.CreateAlertOperationCompleted, userState);
        }
        
        private void OnCreateAlertOperationCompleted(object arg) {
            if ((this.CreateAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAlertCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/UpdateAlert", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateAlert(Alert alert) {
            this.Invoke("UpdateAlert", new object[] {
                        alert});
        }
        
        /// <remarks/>
        public void UpdateAlertAsync(Alert alert) {
            this.UpdateAlertAsync(alert, null);
        }
        
        /// <remarks/>
        public void UpdateAlertAsync(Alert alert, object userState) {
            if ((this.UpdateAlertOperationCompleted == null)) {
                this.UpdateAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAlertOperationCompleted);
            }
            this.InvokeAsync("UpdateAlert", new object[] {
                        alert}, this.UpdateAlertOperationCompleted, userState);
        }
        
        private void OnUpdateAlertOperationCompleted(object arg) {
            if ((this.UpdateAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAlertCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/RemoveAlerts", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveAlerts(Alert[] alerts) {
            this.Invoke("RemoveAlerts", new object[] {
                        alerts});
        }
        
        /// <remarks/>
        public void RemoveAlertsAsync(Alert[] alerts) {
            this.RemoveAlertsAsync(alerts, null);
        }
        
        /// <remarks/>
        public void RemoveAlertsAsync(Alert[] alerts, object userState) {
            if ((this.RemoveAlertsOperationCompleted == null)) {
                this.RemoveAlertsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveAlertsOperationCompleted);
            }
            this.InvokeAsync("RemoveAlerts", new object[] {
                        alerts}, this.RemoveAlertsOperationCompleted, userState);
        }
        
        private void OnRemoveAlertsOperationCompleted(object arg) {
            if ((this.RemoveAlertsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveAlertsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SimpleWorkfloorManagementSuiteNameSpace")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="SimpleWorkfloorManagementSuiteNameSpace", IsNullable=false)]
    public partial class SwmSuiteSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private int employeeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmployeeGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmployeeSettings))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Avatar))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZipCode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Alert))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class BusinessObjectBase {
        
        private int sysIdField;
        
        private int rowVersionField;
        
        /// <remarks/>
        public int SysId {
            get {
                return this.sysIdField;
            }
            set {
                this.sysIdField = value;
            }
        }
        
        /// <remarks/>
        public int RowVersion {
            get {
                return this.rowVersionField;
            }
            set {
                this.rowVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class EmployeeGroup : BusinessObjectBase {
        
        private string nameField;
        
        private string descriptionField;
        
        private Employee[] employeesField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Employee[] Employees {
            get {
                return this.employeesField;
            }
            set {
                this.employeesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class Employee : BusinessObjectBase {
        
        private System.Guid userSysIdField;
        
        private string nameField;
        
        private string firstNameField;
        
        private string addressField;
        
        private ZipCode zipCodeField;
        
        private string privatePhoneNumberField;
        
        private string workPhoneNumberField;
        
        private string cellPhoneNumberField;
        
        private string emailAddress1Field;
        
        private string emailAddress2Field;
        
        private string emailAddress3Field;
        
        private string emailAddress4Field;
        
        private string emailAddress5Field;
        
        private Avatar avatarField;
        
        private EmployeeSettings settingsField;
        
        private string userNameField;
        
        private string passwordField;
        
        private bool administratorField;
        
        /// <remarks/>
        public System.Guid UserSysId {
            get {
                return this.userSysIdField;
            }
            set {
                this.userSysIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public ZipCode ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PrivatePhoneNumber {
            get {
                return this.privatePhoneNumberField;
            }
            set {
                this.privatePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPhoneNumber {
            get {
                return this.workPhoneNumberField;
            }
            set {
                this.workPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CellPhoneNumber {
            get {
                return this.cellPhoneNumberField;
            }
            set {
                this.cellPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress1 {
            get {
                return this.emailAddress1Field;
            }
            set {
                this.emailAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress2 {
            get {
                return this.emailAddress2Field;
            }
            set {
                this.emailAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress3 {
            get {
                return this.emailAddress3Field;
            }
            set {
                this.emailAddress3Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress4 {
            get {
                return this.emailAddress4Field;
            }
            set {
                this.emailAddress4Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress5 {
            get {
                return this.emailAddress5Field;
            }
            set {
                this.emailAddress5Field = value;
            }
        }
        
        /// <remarks/>
        public Avatar Avatar {
            get {
                return this.avatarField;
            }
            set {
                this.avatarField = value;
            }
        }
        
        /// <remarks/>
        public EmployeeSettings Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool Administrator {
            get {
                return this.administratorField;
            }
            set {
                this.administratorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class ZipCode : BusinessObjectBase {
        
        private string codeField;
        
        private string cityField;
        
        private string countryField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class Avatar : BusinessObjectBase {
        
        private byte[] pictureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class EmployeeSettings : BusinessObjectBase {
        
        private bool autoLogonField;
        
        private string autoLogonHostField;
        
        private int logoutTimeoutField;
        
        private bool emailNotificationField;
        
        private string emailAddressField;
        
        private string smtpServerField;
        
        private System.Nullable<int> smtpPortField;
        
        private bool secureConnectionField;
        
        private bool authenticationField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public bool AutoLogon {
            get {
                return this.autoLogonField;
            }
            set {
                this.autoLogonField = value;
            }
        }
        
        /// <remarks/>
        public string AutoLogonHost {
            get {
                return this.autoLogonHostField;
            }
            set {
                this.autoLogonHostField = value;
            }
        }
        
        /// <remarks/>
        public int LogoutTimeout {
            get {
                return this.logoutTimeoutField;
            }
            set {
                this.logoutTimeoutField = value;
            }
        }
        
        /// <remarks/>
        public bool EmailNotification {
            get {
                return this.emailNotificationField;
            }
            set {
                this.emailNotificationField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string SmtpServer {
            get {
                return this.smtpServerField;
            }
            set {
                this.smtpServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SmtpPort {
            get {
                return this.smtpPortField;
            }
            set {
                this.smtpPortField = value;
            }
        }
        
        /// <remarks/>
        public bool SecureConnection {
            get {
                return this.secureConnectionField;
            }
            set {
                this.secureConnectionField = value;
            }
        }
        
        /// <remarks/>
        public bool Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class Alert : BusinessObjectBase {
        
        private string messageField;
        
        private bool visibleField;
        
        private Employee[] employeesField;
        
        private EmployeeGroup[] employeeGroupsField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <remarks/>
        public Employee[] Employees {
            get {
                return this.employeesField;
            }
            set {
                this.employeesField = value;
            }
        }
        
        /// <remarks/>
        public EmployeeGroup[] EmployeeGroups {
            get {
                return this.employeeGroupsField;
            }
            set {
                this.employeeGroupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAlertsCompletedEventHandler(object sender, GetAlertsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAlertsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAlertsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Alert[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Alert[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetGlobalAlertsCompletedEventHandler(object sender, GetGlobalAlertsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGlobalAlertsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGlobalAlertsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Alert[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Alert[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAlertsForEmployeeCompletedEventHandler(object sender, GetAlertsForEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAlertsForEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAlertsForEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Alert[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Alert[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAlertsForEmployeeGroupCompletedEventHandler(object sender, GetAlertsForEmployeeGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAlertsForEmployeeGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAlertsForEmployeeGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Alert[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Alert[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateAlertCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateAlertCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RemoveAlertsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591