//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SwmSuite.Proxy.WebService.LoggingService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoggingServiceSoap", Namespace="SimpleWorkfloorManagementSuiteNameSpace")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessObjectBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConnectionLog[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginLog[]))]
    public partial class LoggingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SwmSuiteSoapHeader swmSuiteSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetConnectionLogsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConnectionLogsByMonthOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoginLogsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoginLogsByMonthOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogLoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LoggingService() {
            this.Url = global::SwmSuite.Proxy.WebService.Properties.Settings.Default.SwmSuite_Proxy_WebService_LoggingService_LoggingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SwmSuiteSoapHeader SwmSuiteSoapHeaderValue {
            get {
                return this.swmSuiteSoapHeaderValueField;
            }
            set {
                this.swmSuiteSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetConnectionLogsCompletedEventHandler GetConnectionLogsCompleted;
        
        /// <remarks/>
        public event GetConnectionLogsByMonthCompletedEventHandler GetConnectionLogsByMonthCompleted;
        
        /// <remarks/>
        public event LogConnectionCompletedEventHandler LogConnectionCompleted;
        
        /// <remarks/>
        public event GetLoginLogsCompletedEventHandler GetLoginLogsCompleted;
        
        /// <remarks/>
        public event GetLoginLogsByMonthCompletedEventHandler GetLoginLogsByMonthCompleted;
        
        /// <remarks/>
        public event LogLoginCompletedEventHandler LogLoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetConnectionLogs", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConnectionLog[] GetConnectionLogs() {
            object[] results = this.Invoke("GetConnectionLogs", new object[0]);
            return ((ConnectionLog[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConnectionLogsAsync() {
            this.GetConnectionLogsAsync(null);
        }
        
        /// <remarks/>
        public void GetConnectionLogsAsync(object userState) {
            if ((this.GetConnectionLogsOperationCompleted == null)) {
                this.GetConnectionLogsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConnectionLogsOperationCompleted);
            }
            this.InvokeAsync("GetConnectionLogs", new object[0], this.GetConnectionLogsOperationCompleted, userState);
        }
        
        private void OnGetConnectionLogsOperationCompleted(object arg) {
            if ((this.GetConnectionLogsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConnectionLogsCompleted(this, new GetConnectionLogsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetConnectionLogsByMonth", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConnectionLog[] GetConnectionLogsByMonth(int year, int month) {
            object[] results = this.Invoke("GetConnectionLogsByMonth", new object[] {
                        year,
                        month});
            return ((ConnectionLog[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConnectionLogsByMonthAsync(int year, int month) {
            this.GetConnectionLogsByMonthAsync(year, month, null);
        }
        
        /// <remarks/>
        public void GetConnectionLogsByMonthAsync(int year, int month, object userState) {
            if ((this.GetConnectionLogsByMonthOperationCompleted == null)) {
                this.GetConnectionLogsByMonthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConnectionLogsByMonthOperationCompleted);
            }
            this.InvokeAsync("GetConnectionLogsByMonth", new object[] {
                        year,
                        month}, this.GetConnectionLogsByMonthOperationCompleted, userState);
        }
        
        private void OnGetConnectionLogsByMonthOperationCompleted(object arg) {
            if ((this.GetConnectionLogsByMonthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConnectionLogsByMonthCompleted(this, new GetConnectionLogsByMonthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/LogConnection", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LogConnection(ConnectionLog connectionLog) {
            this.Invoke("LogConnection", new object[] {
                        connectionLog});
        }
        
        /// <remarks/>
        public void LogConnectionAsync(ConnectionLog connectionLog) {
            this.LogConnectionAsync(connectionLog, null);
        }
        
        /// <remarks/>
        public void LogConnectionAsync(ConnectionLog connectionLog, object userState) {
            if ((this.LogConnectionOperationCompleted == null)) {
                this.LogConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogConnectionOperationCompleted);
            }
            this.InvokeAsync("LogConnection", new object[] {
                        connectionLog}, this.LogConnectionOperationCompleted, userState);
        }
        
        private void OnLogConnectionOperationCompleted(object arg) {
            if ((this.LogConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogConnectionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetLoginLogs", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginLog[] GetLoginLogs() {
            object[] results = this.Invoke("GetLoginLogs", new object[0]);
            return ((LoginLog[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLoginLogsAsync() {
            this.GetLoginLogsAsync(null);
        }
        
        /// <remarks/>
        public void GetLoginLogsAsync(object userState) {
            if ((this.GetLoginLogsOperationCompleted == null)) {
                this.GetLoginLogsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoginLogsOperationCompleted);
            }
            this.InvokeAsync("GetLoginLogs", new object[0], this.GetLoginLogsOperationCompleted, userState);
        }
        
        private void OnGetLoginLogsOperationCompleted(object arg) {
            if ((this.GetLoginLogsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoginLogsCompleted(this, new GetLoginLogsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetLoginLogsByMonth", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginLog[] GetLoginLogsByMonth(int year, int month) {
            object[] results = this.Invoke("GetLoginLogsByMonth", new object[] {
                        year,
                        month});
            return ((LoginLog[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLoginLogsByMonthAsync(int year, int month) {
            this.GetLoginLogsByMonthAsync(year, month, null);
        }
        
        /// <remarks/>
        public void GetLoginLogsByMonthAsync(int year, int month, object userState) {
            if ((this.GetLoginLogsByMonthOperationCompleted == null)) {
                this.GetLoginLogsByMonthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoginLogsByMonthOperationCompleted);
            }
            this.InvokeAsync("GetLoginLogsByMonth", new object[] {
                        year,
                        month}, this.GetLoginLogsByMonthOperationCompleted, userState);
        }
        
        private void OnGetLoginLogsByMonthOperationCompleted(object arg) {
            if ((this.GetLoginLogsByMonthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoginLogsByMonthCompleted(this, new GetLoginLogsByMonthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/LogLogin", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LogLogin(LoginLog loginLog) {
            this.Invoke("LogLogin", new object[] {
                        loginLog});
        }
        
        /// <remarks/>
        public void LogLoginAsync(LoginLog loginLog) {
            this.LogLoginAsync(loginLog, null);
        }
        
        /// <remarks/>
        public void LogLoginAsync(LoginLog loginLog, object userState) {
            if ((this.LogLoginOperationCompleted == null)) {
                this.LogLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogLoginOperationCompleted);
            }
            this.InvokeAsync("LogLogin", new object[] {
                        loginLog}, this.LogLoginOperationCompleted, userState);
        }
        
        private void OnLogLoginOperationCompleted(object arg) {
            if ((this.LogLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogLoginCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SimpleWorkfloorManagementSuiteNameSpace")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="SimpleWorkfloorManagementSuiteNameSpace", IsNullable=false)]
    public partial class SwmSuiteSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private int employeeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmployeeSettings))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Avatar))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZipCode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginLog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConnectionLog))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class BusinessObjectBase {
        
        private int sysIdField;
        
        private int rowVersionField;
        
        /// <remarks/>
        public int SysId {
            get {
                return this.sysIdField;
            }
            set {
                this.sysIdField = value;
            }
        }
        
        /// <remarks/>
        public int RowVersion {
            get {
                return this.rowVersionField;
            }
            set {
                this.rowVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class EmployeeSettings : BusinessObjectBase {
        
        private bool autoLogonField;
        
        private string autoLogonHostField;
        
        private int logoutTimeoutField;
        
        private bool emailNotificationField;
        
        private string emailAddressField;
        
        private string smtpServerField;
        
        private System.Nullable<int> smtpPortField;
        
        private bool secureConnectionField;
        
        private bool authenticationField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public bool AutoLogon {
            get {
                return this.autoLogonField;
            }
            set {
                this.autoLogonField = value;
            }
        }
        
        /// <remarks/>
        public string AutoLogonHost {
            get {
                return this.autoLogonHostField;
            }
            set {
                this.autoLogonHostField = value;
            }
        }
        
        /// <remarks/>
        public int LogoutTimeout {
            get {
                return this.logoutTimeoutField;
            }
            set {
                this.logoutTimeoutField = value;
            }
        }
        
        /// <remarks/>
        public bool EmailNotification {
            get {
                return this.emailNotificationField;
            }
            set {
                this.emailNotificationField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string SmtpServer {
            get {
                return this.smtpServerField;
            }
            set {
                this.smtpServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SmtpPort {
            get {
                return this.smtpPortField;
            }
            set {
                this.smtpPortField = value;
            }
        }
        
        /// <remarks/>
        public bool SecureConnection {
            get {
                return this.secureConnectionField;
            }
            set {
                this.secureConnectionField = value;
            }
        }
        
        /// <remarks/>
        public bool Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class Avatar : BusinessObjectBase {
        
        private byte[] pictureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class ZipCode : BusinessObjectBase {
        
        private string codeField;
        
        private string cityField;
        
        private string countryField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class Employee : BusinessObjectBase {
        
        private System.Guid userSysIdField;
        
        private string nameField;
        
        private string firstNameField;
        
        private string addressField;
        
        private ZipCode zipCodeField;
        
        private string privatePhoneNumberField;
        
        private string workPhoneNumberField;
        
        private string cellPhoneNumberField;
        
        private string emailAddress1Field;
        
        private string emailAddress2Field;
        
        private string emailAddress3Field;
        
        private string emailAddress4Field;
        
        private string emailAddress5Field;
        
        private Avatar avatarField;
        
        private EmployeeSettings settingsField;
        
        private string userNameField;
        
        private string passwordField;
        
        private bool administratorField;
        
        /// <remarks/>
        public System.Guid UserSysId {
            get {
                return this.userSysIdField;
            }
            set {
                this.userSysIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public ZipCode ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PrivatePhoneNumber {
            get {
                return this.privatePhoneNumberField;
            }
            set {
                this.privatePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPhoneNumber {
            get {
                return this.workPhoneNumberField;
            }
            set {
                this.workPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CellPhoneNumber {
            get {
                return this.cellPhoneNumberField;
            }
            set {
                this.cellPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress1 {
            get {
                return this.emailAddress1Field;
            }
            set {
                this.emailAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress2 {
            get {
                return this.emailAddress2Field;
            }
            set {
                this.emailAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress3 {
            get {
                return this.emailAddress3Field;
            }
            set {
                this.emailAddress3Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress4 {
            get {
                return this.emailAddress4Field;
            }
            set {
                this.emailAddress4Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress5 {
            get {
                return this.emailAddress5Field;
            }
            set {
                this.emailAddress5Field = value;
            }
        }
        
        /// <remarks/>
        public Avatar Avatar {
            get {
                return this.avatarField;
            }
            set {
                this.avatarField = value;
            }
        }
        
        /// <remarks/>
        public EmployeeSettings Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool Administrator {
            get {
                return this.administratorField;
            }
            set {
                this.administratorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class LoginLog : BusinessObjectBase {
        
        private System.DateTime dateTimeField;
        
        private Employee employeeField;
        
        /// <remarks/>
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        public Employee Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class ConnectionLog : BusinessObjectBase {
        
        private System.DateTime dateTimeField;
        
        private string clientField;
        
        /// <remarks/>
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetConnectionLogsCompletedEventHandler(object sender, GetConnectionLogsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConnectionLogsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConnectionLogsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConnectionLog[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConnectionLog[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetConnectionLogsByMonthCompletedEventHandler(object sender, GetConnectionLogsByMonthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConnectionLogsByMonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConnectionLogsByMonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConnectionLog[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConnectionLog[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LogConnectionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetLoginLogsCompletedEventHandler(object sender, GetLoginLogsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoginLogsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoginLogsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginLog[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginLog[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetLoginLogsByMonthCompletedEventHandler(object sender, GetLoginLogsByMonthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoginLogsByMonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoginLogsByMonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginLog[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginLog[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LogLoginCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591