//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SwmSuite.Proxy.WebService.HolidayService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HolidayServiceSoap", Namespace="SimpleWorkfloorManagementSuiteNameSpace")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessObjectBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OvertimeEntry[]))]
    public partial class HolidayService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SwmSuiteSoapHeader swmSuiteSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetOvertimeEntriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOvertimeEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOvertimeEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcceptOvertimeEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback DenyOvertimeEntryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HolidayService() {
            this.Url = global::SwmSuite.Proxy.WebService.Properties.Settings.Default.SwmSuite_Proxy_WebService_HolidayService_HolidayService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SwmSuiteSoapHeader SwmSuiteSoapHeaderValue {
            get {
                return this.swmSuiteSoapHeaderValueField;
            }
            set {
                this.swmSuiteSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOvertimeEntriesCompletedEventHandler GetOvertimeEntriesCompleted;
        
        /// <remarks/>
        public event CreateOvertimeEntryCompletedEventHandler CreateOvertimeEntryCompleted;
        
        /// <remarks/>
        public event UpdateOvertimeEntryCompletedEventHandler UpdateOvertimeEntryCompleted;
        
        /// <remarks/>
        public event AcceptOvertimeEntryCompletedEventHandler AcceptOvertimeEntryCompleted;
        
        /// <remarks/>
        public event DenyOvertimeEntryCompletedEventHandler DenyOvertimeEntryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/GetOvertimeEntries", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OvertimeEntry[] GetOvertimeEntries(Employee[] employees, int year) {
            object[] results = this.Invoke("GetOvertimeEntries", new object[] {
                        employees,
                        year});
            return ((OvertimeEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOvertimeEntriesAsync(Employee[] employees, int year) {
            this.GetOvertimeEntriesAsync(employees, year, null);
        }
        
        /// <remarks/>
        public void GetOvertimeEntriesAsync(Employee[] employees, int year, object userState) {
            if ((this.GetOvertimeEntriesOperationCompleted == null)) {
                this.GetOvertimeEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOvertimeEntriesOperationCompleted);
            }
            this.InvokeAsync("GetOvertimeEntries", new object[] {
                        employees,
                        year}, this.GetOvertimeEntriesOperationCompleted, userState);
        }
        
        private void OnGetOvertimeEntriesOperationCompleted(object arg) {
            if ((this.GetOvertimeEntriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOvertimeEntriesCompleted(this, new GetOvertimeEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/CreateOvertimeEntry", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OvertimeEntry CreateOvertimeEntry(OvertimeEntry overtimeEntry) {
            object[] results = this.Invoke("CreateOvertimeEntry", new object[] {
                        overtimeEntry});
            return ((OvertimeEntry)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOvertimeEntryAsync(OvertimeEntry overtimeEntry) {
            this.CreateOvertimeEntryAsync(overtimeEntry, null);
        }
        
        /// <remarks/>
        public void CreateOvertimeEntryAsync(OvertimeEntry overtimeEntry, object userState) {
            if ((this.CreateOvertimeEntryOperationCompleted == null)) {
                this.CreateOvertimeEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOvertimeEntryOperationCompleted);
            }
            this.InvokeAsync("CreateOvertimeEntry", new object[] {
                        overtimeEntry}, this.CreateOvertimeEntryOperationCompleted, userState);
        }
        
        private void OnCreateOvertimeEntryOperationCompleted(object arg) {
            if ((this.CreateOvertimeEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOvertimeEntryCompleted(this, new CreateOvertimeEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/UpdateOvertimeEntry", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OvertimeEntry UpdateOvertimeEntry(OvertimeEntry overtimeEntry) {
            object[] results = this.Invoke("UpdateOvertimeEntry", new object[] {
                        overtimeEntry});
            return ((OvertimeEntry)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOvertimeEntryAsync(OvertimeEntry overtimeEntry) {
            this.UpdateOvertimeEntryAsync(overtimeEntry, null);
        }
        
        /// <remarks/>
        public void UpdateOvertimeEntryAsync(OvertimeEntry overtimeEntry, object userState) {
            if ((this.UpdateOvertimeEntryOperationCompleted == null)) {
                this.UpdateOvertimeEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOvertimeEntryOperationCompleted);
            }
            this.InvokeAsync("UpdateOvertimeEntry", new object[] {
                        overtimeEntry}, this.UpdateOvertimeEntryOperationCompleted, userState);
        }
        
        private void OnUpdateOvertimeEntryOperationCompleted(object arg) {
            if ((this.UpdateOvertimeEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOvertimeEntryCompleted(this, new UpdateOvertimeEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/AcceptOvertimeEntry", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AcceptOvertimeEntry(OvertimeEntry overtimeEntry) {
            this.Invoke("AcceptOvertimeEntry", new object[] {
                        overtimeEntry});
        }
        
        /// <remarks/>
        public void AcceptOvertimeEntryAsync(OvertimeEntry overtimeEntry) {
            this.AcceptOvertimeEntryAsync(overtimeEntry, null);
        }
        
        /// <remarks/>
        public void AcceptOvertimeEntryAsync(OvertimeEntry overtimeEntry, object userState) {
            if ((this.AcceptOvertimeEntryOperationCompleted == null)) {
                this.AcceptOvertimeEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcceptOvertimeEntryOperationCompleted);
            }
            this.InvokeAsync("AcceptOvertimeEntry", new object[] {
                        overtimeEntry}, this.AcceptOvertimeEntryOperationCompleted, userState);
        }
        
        private void OnAcceptOvertimeEntryOperationCompleted(object arg) {
            if ((this.AcceptOvertimeEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcceptOvertimeEntryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SwmSuiteSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SimpleWorkfloorManagementSuiteNameSpace/DenyOvertimeEntry", RequestNamespace="SimpleWorkfloorManagementSuiteNameSpace", ResponseNamespace="SimpleWorkfloorManagementSuiteNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DenyOvertimeEntry(OvertimeEntry overtimeEntry) {
            this.Invoke("DenyOvertimeEntry", new object[] {
                        overtimeEntry});
        }
        
        /// <remarks/>
        public void DenyOvertimeEntryAsync(OvertimeEntry overtimeEntry) {
            this.DenyOvertimeEntryAsync(overtimeEntry, null);
        }
        
        /// <remarks/>
        public void DenyOvertimeEntryAsync(OvertimeEntry overtimeEntry, object userState) {
            if ((this.DenyOvertimeEntryOperationCompleted == null)) {
                this.DenyOvertimeEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDenyOvertimeEntryOperationCompleted);
            }
            this.InvokeAsync("DenyOvertimeEntry", new object[] {
                        overtimeEntry}, this.DenyOvertimeEntryOperationCompleted, userState);
        }
        
        private void OnDenyOvertimeEntryOperationCompleted(object arg) {
            if ((this.DenyOvertimeEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DenyOvertimeEntryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SimpleWorkfloorManagementSuiteNameSpace")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="SimpleWorkfloorManagementSuiteNameSpace", IsNullable=false)]
    public partial class SwmSuiteSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private int employeeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OvertimeEntry))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmployeeSettings))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Avatar))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZipCode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class BusinessObjectBase {
        
        private int sysIdField;
        
        private int rowVersionField;
        
        /// <remarks/>
        public int SysId {
            get {
                return this.sysIdField;
            }
            set {
                this.sysIdField = value;
            }
        }
        
        /// <remarks/>
        public int RowVersion {
            get {
                return this.rowVersionField;
            }
            set {
                this.rowVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class OvertimeEntry : BusinessObjectBase {
        
        private string descriptionField;
        
        private System.DateTime dateTimeStartField;
        
        private System.DateTime dateTimeEndField;
        
        private Employee employeeField;
        
        private OvertimeStatus overtimeStatusField;
        
        private Employee commissionerField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTimeStart {
            get {
                return this.dateTimeStartField;
            }
            set {
                this.dateTimeStartField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTimeEnd {
            get {
                return this.dateTimeEndField;
            }
            set {
                this.dateTimeEndField = value;
            }
        }
        
        /// <remarks/>
        public Employee Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
        
        /// <remarks/>
        public OvertimeStatus OvertimeStatus {
            get {
                return this.overtimeStatusField;
            }
            set {
                this.overtimeStatusField = value;
            }
        }
        
        /// <remarks/>
        public Employee Commissioner {
            get {
                return this.commissionerField;
            }
            set {
                this.commissionerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class Employee : BusinessObjectBase {
        
        private System.Guid userSysIdField;
        
        private string nameField;
        
        private string firstNameField;
        
        private string addressField;
        
        private ZipCode zipCodeField;
        
        private string privatePhoneNumberField;
        
        private string workPhoneNumberField;
        
        private string cellPhoneNumberField;
        
        private string emailAddress1Field;
        
        private string emailAddress2Field;
        
        private string emailAddress3Field;
        
        private string emailAddress4Field;
        
        private string emailAddress5Field;
        
        private Avatar avatarField;
        
        private EmployeeSettings settingsField;
        
        private string userNameField;
        
        private string passwordField;
        
        private bool administratorField;
        
        /// <remarks/>
        public System.Guid UserSysId {
            get {
                return this.userSysIdField;
            }
            set {
                this.userSysIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public ZipCode ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PrivatePhoneNumber {
            get {
                return this.privatePhoneNumberField;
            }
            set {
                this.privatePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPhoneNumber {
            get {
                return this.workPhoneNumberField;
            }
            set {
                this.workPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CellPhoneNumber {
            get {
                return this.cellPhoneNumberField;
            }
            set {
                this.cellPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress1 {
            get {
                return this.emailAddress1Field;
            }
            set {
                this.emailAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress2 {
            get {
                return this.emailAddress2Field;
            }
            set {
                this.emailAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress3 {
            get {
                return this.emailAddress3Field;
            }
            set {
                this.emailAddress3Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress4 {
            get {
                return this.emailAddress4Field;
            }
            set {
                this.emailAddress4Field = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress5 {
            get {
                return this.emailAddress5Field;
            }
            set {
                this.emailAddress5Field = value;
            }
        }
        
        /// <remarks/>
        public Avatar Avatar {
            get {
                return this.avatarField;
            }
            set {
                this.avatarField = value;
            }
        }
        
        /// <remarks/>
        public EmployeeSettings Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool Administrator {
            get {
                return this.administratorField;
            }
            set {
                this.administratorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class ZipCode : BusinessObjectBase {
        
        private string codeField;
        
        private string cityField;
        
        private string countryField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class Avatar : BusinessObjectBase {
        
        private byte[] pictureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public partial class EmployeeSettings : BusinessObjectBase {
        
        private bool autoLogonField;
        
        private string autoLogonHostField;
        
        private int logoutTimeoutField;
        
        private bool emailNotificationField;
        
        private string emailAddressField;
        
        private string smtpServerField;
        
        private System.Nullable<int> smtpPortField;
        
        private bool secureConnectionField;
        
        private bool authenticationField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public bool AutoLogon {
            get {
                return this.autoLogonField;
            }
            set {
                this.autoLogonField = value;
            }
        }
        
        /// <remarks/>
        public string AutoLogonHost {
            get {
                return this.autoLogonHostField;
            }
            set {
                this.autoLogonHostField = value;
            }
        }
        
        /// <remarks/>
        public int LogoutTimeout {
            get {
                return this.logoutTimeoutField;
            }
            set {
                this.logoutTimeoutField = value;
            }
        }
        
        /// <remarks/>
        public bool EmailNotification {
            get {
                return this.emailNotificationField;
            }
            set {
                this.emailNotificationField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string SmtpServer {
            get {
                return this.smtpServerField;
            }
            set {
                this.smtpServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SmtpPort {
            get {
                return this.smtpPortField;
            }
            set {
                this.smtpPortField = value;
            }
        }
        
        /// <remarks/>
        public bool SecureConnection {
            get {
                return this.secureConnectionField;
            }
            set {
                this.secureConnectionField = value;
            }
        }
        
        /// <remarks/>
        public bool Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SwmSuite_v1")]
    public enum OvertimeStatus {
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        Denied,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetOvertimeEntriesCompletedEventHandler(object sender, GetOvertimeEntriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOvertimeEntriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOvertimeEntriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OvertimeEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OvertimeEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateOvertimeEntryCompletedEventHandler(object sender, CreateOvertimeEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOvertimeEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOvertimeEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OvertimeEntry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OvertimeEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateOvertimeEntryCompletedEventHandler(object sender, UpdateOvertimeEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOvertimeEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOvertimeEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OvertimeEntry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OvertimeEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AcceptOvertimeEntryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DenyOvertimeEntryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591